name: Publish package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Fetch release zip
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        version: "latest"
        file: "ordercloud-core-${{ steps.get_version.outputs.VERSION }}.tar.gz"
        token: ${{ secrets.GH_TOKEN }}
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm publish ${{ steps.get_version.outputs.VERSION }}.tar.gz
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}